name: "sndrs.github.io"
description: "Edge-cases, details etc."
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default-template"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post-template"
